# Generated by Django 4.2.5 on 2023-09-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lender_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='code',
            field=models.TextField(max_length=3, verbose_name='Code'),
        ),
    ]
